# Site
repository: ridwansswnto/cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Ridwan Dwi Siswanto
title: DevOps Engineer
email: ridwan.sswanto@gmail.com
# email_title: Email (Email title override)
phone: 08595974xyz6
# phone_title: Phone (Phone title override)
website: https://ridwan-siswanto.com/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  ridwansswnto
linkedin_username: ridwan-dwi
youtube_username: UCiEa1-nvfNhtmsgGV71XyDQ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-RZ6YL7FZXW"
#google_analytics: "G-RZ6YL7FZXW"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Ridwan and I’m a DevOps engineer. As well as administrating systems, managing microservices, I also have a hobbyist in learning coding so I can be a better DevOps. I have worked with some companies to gain teamwork, skills, and collaboration.

  I am most skilled in: <mark>Linux</mark>, <mark>Cloud</mark>, and <mark>Kubernetes</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: PT Global Tiket Network
        sub_title: DevOps Engineer
        caption: September 2019 - present
        link: tiket.com
        quote: >
          Tiket.com is the fastest growing online travel booking in Indonesia. Tiket.com focused heavily on domestic flights and hotels reservation in Indonesia.
        description: | # this will include new lines to allow paragraphs
          - Managing Infrastructure with terraform
          - Managing image with packer 
          - Automate tasks and deployment with ansible
          - Implement gitops with github aciton, and gitlab ci/cd
          - Automate pipeline jenkins with DSL
          - Migrate services to kubernetes
          - Managing manifest kubernetes using kustomize
      - layout: left
        title: PT Nap Info Lintas Nusa
        sub_title: System Administrator
        caption: April 2018 - September 2019
        link: nap.net.id
        quote: >
          NAP Info Lintas Nusa (Matrix NAP Info) is a prominent telecommunication company based in Jakarta, Indonesia.
        description: | # this will include new lines to allow paragraphs
          - Managing users mail address and setting users mail to Microsoft Outlook
          - Managing users PC or Notebook connect to company network and print server
          - Managing and maintaining baremetal servers with VMware and Linux
          - Managing Mail server Zimbra and hardening security for reduce spamm
          - Build Network Monitoring System using cacti

      - layout: left
        title: PT Digital Vision Nusantara
        sub_title: Infrastructure Engineer
        caption: March 2017 - April 2018
        link: www.k-vision.tv
        quote: >
          K-Vision is a pay-TV satellite company in the territory of Indonesia.
        description: | # this will include new lines to allow paragraphs
          - Managing 10 baremetals server with 5 for services (HP Proliant) and 5 for statefull (sun microsystem)
          - Managing Network Infrastructure
          - Build system monitoring for all server (baremetal and vm) using sensu and grafana
          - Redesign network topology to reduce costs
          - Maintaining network connection for branch offie to HQ
          - Managing users mail address and setting users mail to Microsoft Outlook
          - Managing and maintaining Microsoft Active Directory
          - Migration from microsoft exchange to g-suite
          - Managing contact center system (Cisco CUCM and CUIC)

  - title: Certification # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Certified Kubernetes Administrator
        link: https://www.credly.com/badges/6dbbb926-cc56-47d3-9fa5-f824d40ca307
        link_text: Certified Kubernetes Administrator
        description: |
          ![cka](images/cka.jpg "cka")
      - layout: left
        title: GitOps Fundamentals with ArgoCD
        link: https://www.credly.com/badges/6dbbb926-cc56-47d3-9fa5-f824d40ca307
        link_text: GitOps Fundamentals with ArgoCD
        description: |
          ![gitops](images/gitops.jpg "gitops")

  - title: Training # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left
        title: Introduction to GitOps
        link: https://www.credly.com/badges/34c83dfb-fcbb-417d-8213-db2b827e56a0
        link_text: Intro to GitOps
        caption: December 2021
        description: |
          - Training Introduction to GitOps
      - layout: left
        title: Google Cloud Platform
        link: https://www.qwiklabs.com/public_profiles/ecb90b21-4947-4b9a-bd53-a8641e59a20b
        link_text: Google Cloud Platform
        caption: December 2021
        description: |
          - Training Google Cloud and Hands on
      - layout: left
        title: Devops Essentials
        link: https://linuxacademy.com/profile/u/cert/id/196112
        link_text: Devops Essentials
        caption: April 2019
        description: |
          - Training Devops essentials
      - layout: left
        title: Docker
        link: https://linuxacademy.com/profile/u/cert/id/199914
        link_text: Docker
        caption: Mei 2019
        description: |
          - Basics of how Docker works
          - Install the Docker Community Edition
          - Managing images, containers, networks, and volumes
          - Build images using a Dockerfile
          - Tag images and push them to Docker Hub
          - Use Docker Compose to deploy Microservices to Docker
          - Run Docker in Swarm Mode for a more production-ready environment
          - Use Secrets to protect sensitive data like passwords
      - layout: left
        title: Kubernetes
        link: https://linuxacademy.com/profile/u/cert/id/203934
        link_text: Kubernetes
        caption: Mei 2019
        description: |
          - Training Kubernetes
      - layout: left
        title: AWS - CSAA
        link: https://linuxacademy.com/profile/u/cert/id/208136
        link_text: aws
        caption: June 2019
        description: |
          - Training AWS Cloud Solution Architect


    # Certified Kubernetes Administrator 
    # ![cka](/cv/images/cka.jpg "cka")
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Politeknik Pajajaran - ICB Bandung
        sub_title: Associate Degree - Computer Engineering
        caption: 2014 - 2017

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Skill Set
        description: |
          - Kubernetes, Docker
          - Google Cloud Platform
          - Jenkins, Gitlab CI, Github Action
          - Terraform, Packer, Consul
          - Kustomize, ArgoCD
          - Ansible
          - Linux
          - Haproxy, Nginx
          - Bash, Python 
          - Routing Switching
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
